language: generic
services:
  - docker
matrix:
  include:
    - env: ROS_DISTRO=kinetic
    - env: ROS_DISTRO=melodic
    - env: ROS_DISTRO=noetic
install:
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh